### ISSUE TITLE
Some hint about limitation

### ISSUE THREAD

**Issue by fzerorubigd** [Denton-L/aur-autobuild-template#1]
I use this to create my own mirror of aur packages. but there is some limitation. 

1- the `gh-pages` branch only accept files less than 50 MB. so this can not used for package larger than 50 MB, gitlab on the other hand is a better choice since it has the repository limit of 10GB (and I think there is no per file limit) but pushing can take a lot of time and normally travis kill it. (personally I use rsync to push changes to a server) 

2- Its a good idea to have logs inside file, but travis kill the build if it take more than 10 minute without output, which is normal if there is a `C++` code like `pgmodeler` in my case. so I suggest using `tee` to handle the log and pass the output to travis at the same time. 

Thank you!

**Comment by Denton-L** [comment]
Hey, thanks for bringing up these issues!

I'll add in a section about limitations of the build system. in the case of 2, the main reason why I didn't log to output is because Travis kills the job if it produces more than 4 MB of logs. I suppose that's another limitation to add.

**Comment by Denton-L** [comment]
Closed in c7d5997df194b4696683cc6d922a1c8206a97473.
